#!/bin/bash

HOME=`echo ~`
TRASH="${HOME}/.Trash"
TARGET="$@"
ARG1="$1"

if [ -z ${ARG1} ]; then
  echo "trash [delete file name]"
  exit
fi

if [ ! -d ${TRASH} ]; then
  mkdir ${TRASH}
fi

for file in ${TARGET}
do
  if [ -f ${file} ]; then
    echo "'${file}' is move to Trash."
    mv -f ${file} "${HOME}/.Trash/"
  else
    echo "file not found: ${TARGET}"
  fi
done

find "${HOME}/.Trash" -ctime +30 -exec rm -rf {} \;
